env:
  - CPP_COMPILER=g++     C_COMPILER=gcc   OPTION=--enable-cpputest
  - CPP_COMPILER=clang++ C_COMPILER=clang

command:
    - sudo apt-get update
    - sudo apt-get install automake autoconf libtool clang cpputest
    - ./bootstrap
    - CXX="$CPP_COMPILER" CC="$C_COMPILER" ./configure ${OPTION}
    - make clean all
    - make check
