sudo: required

dist: trusty

language: cpp

cache: apt

branches:
  only:
    - master

notifications:
  email:
    - idiotpanzer@gmail.com

addons:
  apt: &apt-global
    sources: &apt-common-sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise
    packages: &apt-common-packages
      - clang-3.8
      - g++-5
      - gcc-5
      - automake
      - autoconf
      - libtool

matrix:
  fast_finish: true
  include:
    - compiler: clang++
      env:
    - compiler: g++
      env:
    - compiler: i686-w64-mingw32-g++
      env: MINGW32=1
      addons:
        apt:
          sources:
            - *apt-common-sources
            - sourceline: 'ppa:tobydox/mingw-x-trusty'
            - sourceline: 'deb http://ppa.launchpad.net/tobydox/mingw-x-trusty/ubuntu trusty main'
          packages:
            - *apt-common-packages
            - mingw32-x-binutils
            - mingw32-x-gcc
            - mingw32-x-runtime

before_install:

install:

before_script:
  # g++
  - if [ "${CXX}" = 'g++' ]; then export CXX=g++-5; fi
  # clang
  - if [ "${CXX}" = 'clang++' ]; then export CXX=clang++-3.8; fi
  # mingw32
  - if [ "${MINGW32}" = '1' ]; then export CXX=i686-w64-mingw32-g++; fi
  # mingw64
  - if [ "${MINGW64}" = '1' ]; then export CXX=x86_64-w64-mingw32-g++; fi

script:
  - if [ "${CXX}" = 'g++-5' ]; then ./bootstrap && ./configure && make; fi
  # clang
  - if [ "${CXX}" = 'clang++-3.8' ]; then ./bootstrap && ./configure && make; fi
  # mingw32
  - if [ "${MINGW32}" = '1' ]; then ./cross-i686-w64-mingw32.sh; fi
  # mingw64
  #- if [ "${MINGW64}" = '1' ]; then ./cross-x86_64-w64-mingw32.sh; fi
  
