sudo: required

dist: trusty

language: cpp

cache: apt

branches:
  only:
    - master

notifications:
  email:
    - idiotpanzer@gmail.com

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - ninja-build
      - cpputest
      - gcc-4.9
      - g++-4.9

before_install:

install:

before_script:
  - mkdir build
  - cd build
  - CXX=g++-4.9 CC=gcc-4.9 cmake -G Ninja ..

script:
  - ninja
  - ninja images
  - ctest
