sudo: required

dist: trusty

language: cpp

cache: apt

branches:
  only:
    - master

notifications:
  email:
    - idiotpanzer@gmail.com

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - ninja-build
      - cpputest
      - gcc-4.9
      - g++-4.9
      - libc6-dev-i386
      - linux-headers-generic

# Use https (public access) instead of git for git-submodules. This modifies only Travis-CI behavior!
# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  
install:

before_script:
  - mkdir build
  - cd build
  - CXX=g++-4.9 CC=gcc-4.9 cmake -G Ninja ..

script:
  - ninja
  - ninja images
  - ctest
