sudo: required

dist: trusty

language: cpp

cache: apt

branches:
  only:
    - master

notifications:
  email:
    - idiotpanzer@gmail.com

addons:
  apt: &apt-global
    sources: &apt-common-sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise
    packages: &apt-common-packages
      - clang-3.8
      - g++-5
      - gcc-5
      - automake
      - autoconf
      - libtool

matrix:
  fast_finish: true
  include:
    - compiler: clang++
      env:
    - compiler: g++
      env:
    - compiler: i686-w64-mingw32-g++
      env:
        - MINGW32=1
        - APT_REPOS="ppa:tobydox/mingw-x-trusty"
        - APT_PACKAGES="p7zip mingw32-x-gcc"
        - MINGW_ROOT=/opt/mingw32
        - MINGW_PREFIX=i686-w64-mingw32
      addons:
        apt:
          sources:
            - *apt-common-sources
            - tobydox-mingw-x-trusty
          packages:
            - *apt-common-packages
            - mingw32-x-binutils
            - mingw32-x-gcc
            - mingw32-x-runtime

before_install:
  - sudo dpkg --add-architecture i386
  - if [ "$MINGW_ROOT" ]; then for APT_REPO in $APT_REPOS; do sudo add-apt-repository -y $APT_REPO; done; fi
  - if [ "$MINGW_ROOT" ]; then sudo apt-get update -qq || true; fi
  - if [ "$MINGW_ROOT" ]; then sudo apt-get install -qq -y --no-install-recommends $APT_PACKAGES; fi
  - if [ "$MINGW_ROOT" ]; then export PATH=$MINGW_ROOT/bin:$PATH; fi

install:

before_script:
  # g++
  - if [ "${CXX}" = 'g++' ]; then export CXX=g++-5; fi
  # clang
  - if [ "${CXX}" = 'clang++' ]; then export CXX=clang++-3.8; fi
  # mingw32
  - if [ "${MINGW32}" = '1' ]; then export CXX=i686-w64-mingw32-g++; fi
  # mingw64
  - if [ "${MINGW64}" = '1' ]; then export CXX=x86_64-w64-mingw32-g++; fi

script:
  - if [ "${CXX}" = 'g++-5' ]; then ./bootstrap && ./configure && make; fi
  # clang
  - if [ "${CXX}" = 'clang++-3.8' ]; then ./bootstrap && ./configure && make; fi
  # mingw32
  - if [ "${MINGW32}" = '1' ]; then ./cross-i686-w64-mingw32.sh; fi
  # mingw64
  #- if [ "${MINGW64}" = '1' ]; then ./cross-x86_64-w64-mingw32.sh; fi
  
