sudo: required

dist: trusty

language: cpp

cache: apt

branches:
  only:
    - master
    - cmake_ninja

notifications:
  email:
    - idiotpanzer@gmail.com

addons:
  apt:
    sources:
      - george-edison55-cmake-3.x
    packages:
      - cmake
      - cmake-data
      - ninja-build
      - cpputest

before_install:

install:

before_script:
  - mkdir build
  - cd build
  - cmake -G Ninja ..

script:
  - ninja
  - ninja images
  - ctest
