sudo: required

dist: trusty

language: cpp

cache: apt

branches:
  only:
    - master

notifications:
  email:
    - idiotpanzer@gmail.com

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_install:

install:

before_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_MAKE_PROGRAM=make ..

script:
  - cd build
  - make
